# global.toml
[settings]
default_target_type="template"
#########################################
# FILE MAPPINGS
#########################################
[terminal.files]
"files/kitty" = "~/.config/kitty"
"files/gitconfig" = "~/.gitconfig"
"files/zprofile" = "~/.zprofile"
"files/zshrc" = "~/.zshrc"
"files/oh-my-zsh/custom" = "~/.oh-my-zsh/custom"

[themes.files]
"files/themes" = { target = "~/.themes", type = "symbolic" }
"files/icons" = { target = "~/.icons", type = "symbolic" }

[desktop.files]
"files/btop" = "~/.config/btop"
"files/cava" = "~/.config/cava"
"files/fastfetch" = { target = "~/.config/fastfetch", type = "symbolic" }
"files/hypr" = { target = "~/.config/hypr", type = "symbolic" }
"files/waybar" = { target = "~/.config/waybar", type = "symbolic" }
"files/rofi" = { target = "~/.config/rofi", type = "symbolic" }
"files/swaync" = { target = "~/.config/swaync", type = "symbolic" }
"files/wlogout" = { target = "~/.config/wlogout", type = "symbolic" }
"files/swappy" = "~/.config/swappy"

[apps.files]
"files/gh/config.yml" = "~/.config/gh/config.yml"
"files/nvim" = "~/.config/nvim"
"files/ranger" = "~/.config/ranger"
"files/Thunar" = "~/.config/Thunar"
"files/wallust" = "~/.config/wallust"
"files/textfox" = { target = "~/textfox", type = "symbolic" }

[gui_libs.files]
"files/gtk-3.0" = "~/.config/gtk-3.0"
"files/gtk-4.0" = "~/.config/gtk-4.0"
"files/Kvantum" = "~/.config/Kvantum"
"files/qt5ct" = "~/.config/qt5ct"
"files/qt6ct" = "~/.config/qt6ct"
"files/nwg-look" = "~/.config/nwg-look"

[system_user.files]
"files/dconf-settings.ini" = "~/.config/dconf-settings.ini"
"files/mimeapps.list" = "~/.config/mimeapps.list"
"files/user-dirs.dirs" = "~/.config/user-dirs.dirs"

# Root packages
[grub.files]
"files/grub/themes" = { target = "/boot/grub/themes", type = "symbolic" }

[sddm.files]
"files/sddm/sddm.conf" = "/etc/sddm.conf"
"files/sddm/wallpaper_update.sh" = "/usr/share/sddm/scripts/wallpaper_update.sh"

[plymouth.files]
"files/plymouth/plymouthd.conf" = "/etc/plymouth/plymouthd.conf"
"files/plymouth/onePiece-plymouth" = { target = "/usr/share/plymouth/themes/onePiece-plymouth", type = "symbolic" }


[systemd.files]
"files/services" = "/etc/systemd/system"
"files/systemd" = "~/.config/systemd"

